export const TODO_ITEM_CREATE = 'TODO_ITEM_CREATE';
export const TODO_ITEM_REMOVE = 'TODO_ITEM_REMOVE';
export const TODO_ITEM_COMPLETE = 'TODO_ITEM_COMPLETE';
export const TODO_ITEM_MODIFY = 'TODO_ITEM_MODIFY';
export const TODO_ITEM_SEARCH = 'TODO_ITEM_SEARCH';
